version: '3'
services:
  web:
    build:
      context: ./docker/PhpApache
      dockerfile: Dockerfile
    container_name: apache_php_8
    ports:
      - 8080:80
    volumes:
      # srcディレクトリに案件毎のgitリポジトリを置く想定
      # 例ではhtmlディレクトリとしているが、適宜変更する。
      - ./src/html/:/var/www/html
    tty: true
  db:
    image: mysql
    container_name: mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    tty: true

